{% set version = "2018.04.05" %} 
{% set sha256 = "c9310a371f839f871e157bd2b584e6e2299b0d886f8eb820d1c319b0f06b3690" %}

about:
  home: 'https://github.com/lindenb/jvarkit'
  license: "MIT License"
  summary: "Java utilities for Bioinformatics"

package:
  name: jvarkit
  version: {{ version }}

build:
  number: 0

source:
  fn:  v{{ version }}.zip
  sha256: {{ sha256 }}
  url: https://github.com/lindenb/jvarkit/archive/v{{ version }}.zip

requirements:
  build:
      - java-jdk >=8,<9
      - wget
      - make
      - unzip
  run:
      - java-jdk >=8,<9
      - awk

test:
    commands:
      - jvarkit bam2raster -h
      - jvarkit bam2svg -h
      - jvarkit bioalcidaejdk -h
      - jvarkit cytoband2svg -h
      - jvarkit findavariation -h
      - jvarkit groupbygene -h
      - jvarkit illuminadir -h
      - jvarkit indexcovjfx -h
      - jvarkit lowresbam2raster -h
      - jvarkit ngsfilessummary -h
      - jvarkit prettysam -h
      - jvarkit sam2tsv -h
      - jvarkit samjdk -h
      - jvarkit tview -h
      - jvarkit tviewserver -h
      - jvarkit vcf2svg -h
      - jvarkit vcf2table -h
      - jvarkit vcffilterjdk -h
      - jvarkit vcfpeekvcf -h
      - jvarkit vcfserver -h
      - jvarkit vcffilterso -h
      - jvarkit xsltstream -h


extra:
   skip-lints:
      - uses_javajdk
